![SIMEM_logo_1.png](../../assets/SIMEM_logo_1.png)

[SiMEM](https://www.simem.co/)

## Objetivos de este Notebook

* Explicar cómo se puede consultar el catálogo de conjuntos de datos que se publican en SiMEM.
* Explicar cómo consultar la información de un conjunto de datos determinado.
* Demostrar cómo hacer filtros especializados en un conjunto de datos determinado.

### 1. Instalación

In [2]:
from pydataxm.pydatasimem import ReadSIMEM, VariableSIMEM, CatalogSIMEM

### 2. Catálogos

##### CatalogSIMEM

In [3]:
catalogo_dataset = CatalogSIMEM(catalog_type='Datasets').get_data()
catalogo_dataset.head()

  idDataset  ... tipoPublicacion
0    a704ee  ...         Público
1    d808d4  ...         Público
2    2106b8  ...         Público
3    B1009C  ...         Público
4    E4CE10  ...         Público

[5 rows x 10 columns]

In [4]:
nombre_dataset = 'Precio de Bolsa'

idDataset = catalogo_dataset[
    catalogo_dataset['nombreConjuntoDatos']
        .str.lower()
        .str.contains(nombre_dataset.lower(), na=False)
]

idDataset[['idDataset', 'nombreConjuntoDatos']]

    idDataset        nombreConjuntoDatos
199    EC6945    Precio de bolsa horario
346    96D56E  Precio de bolsa ponderado

In [5]:
catalogo_variables = CatalogSIMEM(catalog_type='Variables').get_data()
catalogo_variables.head()

  idDataset  ... fechaFin
0    71a7b9  ...     None
1    bd583d  ...     None
2    e427a2  ...     None
3    86d298  ...     None
4    15df39  ...     None

[5 rows x 9 columns]

In [6]:
nombre_variable = 'Precio de Bolsa'

idDataset = catalogo_variables[
    catalogo_variables['nombreVariable']
        .str.lower()
        .str.contains(nombre_variable.lower(), na=False)
]

idDataset[['idDataset', 'nombreDataset', 'nombreVariable']]

    idDataset  ...                                  nombreVariable
129    EC6945  ...                             Precio de bolsa TIE
130    3F3687  ...                             Precio de bolsa TIE
193    EC6945  ...                        Precio de bolsa nacional
194    3F3687  ...                        Precio de bolsa nacional
776    f2081a  ...  Precio de bolsa ponderado con compras en bolsa
777    7c8129  ...  Precio de bolsa ponderado con compras en bolsa
778    96D56E  ...  Precio de bolsa ponderado con compras en bolsa
928    EC6945  ...                   Precio de bolsa internacional
929    3F3687  ...                   Precio de bolsa internacional
953    96D56E  ...   Precio de bolsa ponderado con generación real
954    7c8129  ...   Precio de bolsa ponderado con generación real

[11 rows x 3 columns]

##### VariableSIMEM

In [7]:
listado_variables_simem = VariableSIMEM.get_collection()
listado_variables_simem.head()

                      CodigoVariable  ...                                        Dimensiones
0             AportesHidricosEnergia  ...  [CodigoSerieHidrologica, RegionHidrologica, Fe...
1                AportesHidricosMasa  ...  [CodigoSerieHidrologica, RegionHidrologica, Fe...
2           AportesHidricosMasaPSS95  ...  [CodigoSerieHidrologica, RegionHidrologica, Fe...
3  BanderaAutorizacionDesvFueraBanda  ...                 [CodigoPlanta, Version, FechaHora]
4              BanderaArranqueGIdeal  ...                 [CodigoPlanta, Version, FechaHora]

[5 rows x 3 columns]

In [8]:
nombre_variable = 'Precio de Bolsa'

cod_variable = listado_variables_simem[
    listado_variables_simem['Nombre']
        .str.lower()
        .str.contains(nombre_variable.lower(), na=False)
]

cod_variable[['CodigoVariable', 'Nombre']]

    CodigoVariable                                          Nombre
144         PB_Int                   Precio de bolsa internacional
145         PB_Nal                        Precio de bolsa nacional
146         PB_Tie                             Precio de bolsa TIE
158           PPBO  Precio de bolsa ponderado con compras en bolsa
159      PPBOGReal   Precio de bolsa ponderado con generacion real

### 3. Consulta de datos

##### ReadSIMEM

In [9]:
id_dataset = 'EC6945'
fecha_inicio = '2026-01-01'
fecha_fin = '2026-02-28'

simem = ReadSIMEM(dataset_id=id_dataset, start_date=fecha_inicio, end_date=fecha_fin)

****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************

In [10]:
data = simem.main()
data

Inicio consulta sincronica
Creacion url: 0.002674579620361328
Extraccion de registros: 6.547282695770264
End of data extracting process
****************************************************************************************************

      CodigoVariable            FechaHora  ... Version     Valor
0             PB_Int  2026-01-31T14:00:00  ...     TXF  192.8123
1             PB_Nal  2026-01-31T14:00:00  ...     TX1  204.7811
2             PB_Int  2026-01-31T14:00:00  ...     TX1  189.5000
3             PB_Tie  2026-01-31T22:00:00  ...     TXF  203.3123
4             PB_Tie  2026-01-31T13:00:00  ...     TXR  192.8242
...              ...                  ...  ...     ...       ...
19219         PB_Nal  2026-02-21T06:00:00  ...     TX1   98.4595
19220         PB_Int  2026-02-21T19:00:00  ...     TXR  158.6179
19221         PB_Int  2026-02-21T08:00:00  ...     TXR   99.9719
19222         PB_Tie  2026-02-21T16:00:00  ...     TXF  105.4748
19223         PB_Int  2026-02-21T10:00:00  ...     TXF   99.9718

[19224 rows x 6 columns]

In [11]:
filtro = [["CodigoVariable","=","PB_Nal"],["Version","=","TXF"],["Valor","between",["95","150"]]]
simem.set_filter(filters=filtro)

In [12]:
simem.get_filters()

[{'Fd': 'CodigoVariable', 'Op': 'eq', 'Vl': 'PB_Nal', 'Lg': 'and'},
 {'Fd': 'Version', 'Op': 'eq', 'Vl': 'TXF', 'Lg': 'and'},
 {'Fd': 'Valor', 'Op': 'btw', 'Vl': '95,150', 'Lg': 'and'}]

In [13]:
data_filtro = simem.main(filter=True)
data_filtro

Inicio consulta sincronica
Creacion url: 0.00064849853515625
Extraccion de registros: 29.84244441986084
End of data extracting process
****************************************************************************************************

    CodigoVariable            FechaHora  ... Version     Valor
0           PB_Nal  2026-01-01T10:00:00  ...     TXF  103.0408
1           PB_Nal  2026-01-19T09:00:00  ...     TXF  111.7142
2           PB_Nal  2026-01-19T02:00:00  ...     TXF  105.7042
3           PB_Nal  2026-01-19T06:00:00  ...     TXF  149.7142
4           PB_Nal  2026-01-19T05:00:00  ...     TXF  111.7142
..             ...                  ...  ...     ...       ...
801         PB_Nal  2026-02-21T03:00:00  ...     TXF  107.1365
802         PB_Nal  2026-02-21T09:00:00  ...     TXF  107.1365
803         PB_Nal  2026-02-21T01:00:00  ...     TXF  107.1365
804         PB_Nal  2026-02-21T20:00:00  ...     TXF  120.7825
805         PB_Nal  2026-02-21T15:00:00  ...     TXF  107.1365

[806 rows x 6 columns]

##### VariableSIMEM

In [14]:
start_date = '2026-01-01'
end_date = '2026-02-28'
codigoVar = 'PB_Nal'
filtro = ["Valor",">=","120"]

data_var = VariableSIMEM(start_date=start_date, end_date=end_date, 
                         cod_variable=codigoVar, filters=filtro).get_data()
data_var

****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0005474090576171875
Extraccion de registros: 4.676637172698975
End of data extracting process
****************************************************************************************************
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Versiones de factura para la liquidación mensual"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0003597736358642578
Extraccion de registros: 3.201826810836792
End of data extracting process
****************************************************************************************************

                            CodigoVariable  ...     Valor
FechaHora           Version                 ...
2026-01-31T08:00:00 TX3             PB_Nal  ...  208.1695
2026-01-31T02:00:00 TX3             PB_Nal  ...  208.1695
2026-01-31T22:00:00 TX3             PB_Nal  ...  218.6695
2026-01-31T09:00:00 TX3             PB_Nal  ...  208.1695
2026-01-31T20:00:00 TX3             PB_Nal  ...  218.6695
...                                    ...  ...       ...
2026-02-24T20:00:00 TXF             PB_Nal  ...  126.9492
2026-02-24T05:00:00 TXF             PB_Nal  ...  120.5422
2026-02-21T19:00:00 TXF             PB_Nal  ...  165.7825
2026-02-21T18:00:00 TXF             PB_Nal  ...  120.7825
2026-02-21T20:00:00 TXF             PB_Nal  ...  120.7825

[891 rows x 4 columns]